export interface INews {
    Id: number,
    Title: string,
    Description: string,
    Content: string,
    Image: string,
    CategoryId: number,
    Status: number,
    CreatedTime: string,
    ModifiedTime: string,
    CreateBy: string,
    ModifiedBy: string,
    Author: string,
    ViewCount: number,
    Tags:string,
}